// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EvoCodeGen
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidEvoCodeGenPackageString = "9979a4b5-a2d3-4924-b788-2e806545c5e1";
        public static Guid guidEvoCodeGenPackage = new Guid(guidEvoCodeGenPackageString);

        public const string guidEvoCodeGenPackageCmdSetString = "14080aa9-4ace-4ed4-8c93-6192803a50da";
        public static Guid guidEvoCodeGenPackageCmdSet = new Guid(guidEvoCodeGenPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EvoCodeGenWindowCommandId = 0x0100;
    }
}