// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EvoCodeGen
{
    internal sealed partial class Vsix
    {
        public const string Id = "EvoCodeGen.54bf56dc-7b53-40ae-ad62-e74d6579a612";
        public const string Name = "Evo Code Generator";
        public const string Description = @"Evo Code Generator allows you to generate code using your own templates (typically placed in your project within ""_Templates"" folder) and with different kind of model.
Use generator to generate your model like ""JSON source folder"" or ""SQL models generator"".
Your template should have "".sbn"" and language supported is Scriban.Evo Code ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "MM_MSDN";
        public const string Tags = "code generator, code generation, code template, code templating, generator, templates, scriban, textrude";
    }
}
